/* RELATÓRIO GERAL DE TODOS OS CLIENTES */

/* RELATÓRIO GERAL DOS HOMENS */

/* RELATÓRIO GERAL DAS MULHERES */

/* QUANTIDADE DE HOMENS E MULHERES */

/* IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RJ E NÃO TENHAM CELULAR */
