CREATE DATABASE PROCEDIMENTOS;
USE PROCEDIMENTOS;

/* PARA UTILIZAR PROCEDURES, É PRECISO MUDAR O DELIMITER 
   NESSE CASO, MUDAMOS DE ; PARA / */
DELMITER /

/* CRIANDO PROCEDURES BÁSICOS */
CREATE PROCEDURE PROCEDIMENTO()
BEGIN
	
	SELECT "UNIVERSIDADE DOS DADOS" AS EMPRESA;

END
/

CALL PROCEDIMENTO()/

/* CRIANDO PROCEDURES COM PARAMÊTROS */
CREATE PROCEDURE CONTA(NUM1 INT, NUM2 INT)
BEGIN

	SELECT NUM1 + NUM2 AS CONTA;

END
/

CALL CONTA(100,500)/

/* PROCEDURE USADO EM CASOS REAIS */
CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
)/

/* O IDCURSO NÃO ENTRA NOS PARAMETROS POIS É UMA PRIMARY KEY
   COM AUTO_INCREMENT, NÃO SENDO NECESSÁRIO TE-LO NOS PARAMETROS
   APENAS SER PASSADO NO INSERT */
CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30),
						   P_HORAS INT(3),
						   P_PRECO FLOAT(10,2))
BEGIN

	INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_PRECO);

END
/

CREATE PROCEDURE CONS_CURSO(ID_CURSO INT)
BEGIN

	SELECT IDCURSO, NOME, HORAS, VALOR
	FROM CURSOS
	WHERE ID_CURSO = IDCURSO;

END
/

CALL CAD_CURSO("SQL SERVER", 30, 300)/
CALL CAD_CURSO("DJANO - PYTHON", 60, 150.50)/
CALL CAD_CURSO("JAVA", 150, 200)/

CALL CONS_CURSO(2)/