CREATE DATABASE COMERCIO;
USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT, 
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,

	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT, 
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,

	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');

INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);

INSERT INTO TELEFONE VALUES(NULL,'CEL','78458743',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','56576876',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','87866896',1);
INSERT INTO TELEFONE VALUES(NULL,'COM','54768899',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','99667587',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','78989765',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99766676',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','66687899',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','89986668',5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88687909',2);

/* CRIAÇÃO DO VIEW PARA UM RELATORIO COMPLETO E ORDENADO PELO NOME */
CREATE VIEW V_RELATORIO AS
SELECT C.NOME, C.SEXO,IFNULL (C.EMAIL, "*******") AS "E-MAIL",
	   E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO,
	   T.NUMERO, T.TIPO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
ORDER BY C.NOME;
/* PROJEÇÃO */
SELECT * FROM V_RELATORIO;


/* CRIAÇÃO DA VIEW PARA ENDEREÇOS E ORDENADO PELO ESTADO */
CREATE VIEW V_ENDERECOS AS
SELECT E.ESTADO,E.CIDADE, E.BAIRRO, E.RUA,
       C.IDCLIENTE, C.NOME, C.SEXO
FROM ENDERECO E
INNER JOIN CLIENTE C
ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY ESTADO;
/* PROJEÇÃO */
SELECT * FROM V_ENDERECOS;


/* CRIAÇÃO DO VIEW PARA TELEFONES */
CREATE VIEW V_TELEFONES AS
SELECT T.TIPO, T.NUMERO,
	   C.IDCLIENTE, C.NOME, C.SEXO
FROM TELEFONE T
INNER JOIN CLIENTE C
ON C.IDCLIENTE = T.ID_CLIENTE
ORDER BY TIPO;
/* PROJEÇÃO */
SELECT * FROM V_TELEFONES;


/* CRIAÇÃO DE UM UPDATE PARA AJEITAR O ERRO DE UM SEXO DO CLIENTE */
UPDATE CLIENTE
SET SEXO = "F"
WHERE NOME IN ("DANIELE", "LORENA", "ELAINE", "CARMEM");
