/* LINGUAGEM DML - DATA MANIPULATION LANGUAGE - LINGUAGEM DE MANIPULAÇÃO DE DADOS */

CREATE DATABASE DML_LANG;
USE DML_LANG;

CREATE TABLE PEOPLE (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(50),
  AGE INT,
  SEX CHAR(1)
);

/* INSERT */
INSERT INTO PEOPLE
VALUES
(NULL, "Jean", 20, "M");

/* FILTER */
SELECT * FROM PEOPLE
WHERE SEX = "F";

/* UPDATE */
UPDATE PEOPLE
SET NAME = "João"
WHERE ID = 1;

/* DELETE */
DELETE FROM PEOPLE
WHERE ID = 1;
