CREATE DATABASE VENDEDORES;
USE VENDEDORES;

CREATE TABLE VENDEDOR(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	JANEIRO FLOAT(10,2),
	FEVEREIRO FLOAT(10,2),
	MARCO FLOAT(10,2)
);

INSERT INTO VENDEDOR
VALUES
(NULL, "CARLOS", "M", 12381.12, 125431.51, 53461.54),
(NULL, "ROBERTO", "M", 123512.12, 54632.51, 65471.54),
(NULL, "JULIA", "F", 765123.12, 23462.51, 12355.54),
(NULL, "LUIZA", "F", 381.12, 14244.51, 876543.54),
(NULL, "LUCAS", "M", 566412.12, 8864742.51, 246886.54);

/* MAX - TRAZ O VALOR MÁXIMO DE UMA COLUNA 
		 -> O MAIOR VALOR PRESENTE NA COLUNA*/

SELECT MAX(FEVEREIRO) AS MAIOR_FEV
FROM VENDEDOR;

/* MIN - TRAZ O VALOR MINÍMO DE UMA COLUNA 
		 -> O MENOR VALOR PRESENTE NA COLUNA*/

SELECT MIN(FEVEREIRO) AS MENOR_FEV
FROM VENDEDOR;

/* AVG - TRAZ O VALOR MÉDIO DE UMA COLUNA 
		 -> ELE SOMA OS VALORES DA COLUNA E DIVIDE PELO NÚMERO DE LINHAS*/

SELECT AVG(FEVEREIRO) AS MÉDIA_FEV
FROM VENDEDOR;

/* VÁRIAS FUNÇÕES */

SELECT MAX(JANEIRO) AS MAX_JAN,
	   MIN(JANEIRO) AS MIN_JAN,
	   AVG(JANEIRO) AS MÉDIA_JAN
FROM VENDEDOR;

/* TRUNCATE - TRAVA AS CASAS DECIMAIS DE UM NÚMERO */

SELECT MAX(JANEIRO) AS MAX_JAN,
	   MIN(JANEIRO) AS MIN_JAN,
	   TRUNCATE(AVG(JANEIRO), 2) AS MÉDIA_JAN
FROM VENDEDOR;

/* SUM - FAZ A SOMA DOS VALORES DE UMA COLUNA */

SELECT SUM(JANEIRO) AS SUM_JAN,
	   SUM(FEVEREIRO) AS SUM_FEV,
	   SUM(MARCO) AS SUM_MAR
FROM VENDEDOR;

/* VENDAS POR SEXO */

SELECT SEXO, SUM(MARCO) AS TOTAL_MAR
FROM VENDEDOR
GROUP BY SEXO;
